#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Upload your camera roll to object storage.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Craig Rachel
your_link                                 : https://craigrachel.com                     
your_city                                 : Texas                                
email_address                             : craig@datapulter.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : craigrachel
github_username                           : crachel
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Use With Any Provider
    description                           : Backblaze B2, Amazon Web Services (AWS), DigitalOcean Spaces, Minio, and any S3-compliant provider.
    fontawesome_icon_name                 : handshake

  - title                                 : Keep Original File Format
    description                           : Upload your data exactly as it appears on your device.
    fontawesome_icon_name                 : file
    
  - title                                 : Compare File Hashes
    description                           : Ensure the integrity of your data after it has been transferred.
    fontawesome_icon_name                 : key

  - title                                 : Fully Supports SSL (HTTPS)
    description                           : Protect data in transit.
    fontawesome_icon_name                 : user-secret

  - title                                 : No Advertisements
    description                           : Manage your data without distracting ads.
    fontawesome_icon_name                 : ban

  - title                                 : 100% Written in Swift
    description                           : Actively maintained by one developer who also uses the app. 
    fontawesome_icon_name                 : code

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
